### ISSUE TITLE
Show json Body/Response not toggling

### ISSUE THREAD

**Issue by Garito** [heynemann/flask-debugtb-elasticsearch#1]
Hi!
I'm trying to debug a slow query by using this extension but when I try to toggle the Show Json Body or the Show Json Response it doesn't work (doesn't do nothing)

Seems to me a javascript error since the html code has the information setted to the DOM (I can inspect both the query and the response)

This information is the whole point of the extension so without this is pretty useless

Thanks!

**Comment by ghost** [comment]
@Garito  i ran into the same issue I resolved it on a fork.

https://github.com/heynemann/flask-debugtb-elasticsearch/pull/2

**Comment by heynemann** [comment]
Released in 0.1.4.
